networks:
  moodle-network:
    driver: bridge

services:
  moodle:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db
    environment:
      - MOODLE_DBTYPE=pgsql
      - MOODLE_DBHOST=db
      - MOODLE_DBUSER=moodle
      - MOODLE_DBPASS=senha
      - MOODLE_DBNAME=moodle
    volumes:
      - moodledata:/var/www/html/moodledata

  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    environment:
      - POSTGRES_USER=moodle
      - POSTGRES_PASSWORD=senha
      - POSTGRES_DB=moodle
    volumes:
      - postgresdata:/var/lib/postgresql/data
  
volumes:
  moodledata:
    driver: local
  postgresdata:
    driver: local